language: bash
cache:
  directories:
    - "$HOME/bin/terraform/"
env:
  global:
    - TF_VERSION=0.13.5
    - TF_INIT_CLI_OPTIONS="-input=false"
    - TF_PLAN_CLI_OPTIONS="-lock=false -input=false"
    - TF_APPLY_CLI_OPTIONS="-auto-approve -input=false"
    - TF_OUTPUT_CLI_OPTIONS=""
    - secure: dpHmya6E8N9IRHcFSoGjclfWvIY0MjW+jZ1OpUM1DQgL4B1+6o2o+OaTSJ0/4/2oWnUU9j8F1A6ARmu1GVGT6pDvcj58I8cfQVpuQSBzFMbykYCHiIXWY9EUUiacvQenOrcf7r44/EoNUO9pFod/ISzWM28pd359GMACQNzIF5rPy3B9AAvv4VQdlfTptaVD+LoKVjA1uRtfkOrsGrSPu7BPTRMW/+biUvdyEccia/mT5fvvYrs1xgpYFoYOVa8o/sQ9Iv7dlBM8s1JlmAxh706eaWZPWPpV2gakKxJEdrbbDcNAegTbdW0W3HQYxY9rp3Y2XE6nQ3FztKpXh57isMSDPUEXn+vvEV0VGsML75P81bBLeNpfWU+fSbtrdotvO21vzA6gXK6OH1xu+36Qc5RlyWtqM9jaIG96+hgn3E/MKQj5MXLggQIGjX8//tEBS9jg/hgTIobLXX0WTGuO6+ZHLbDAoI9qFNp9FKBy/nDc2C/rSWH1GI5VoS2TB0NjPU6SprErFwizrXXqFuzgQggEM2R2eI0JXb0H0kLcLS7f3b3kOOtDDSquv8fkueaQvfcV5TnxgGE/Z6F3jKhh6IcSSxVuy7avMD4zVsFPAcjybICD88csd0EIf849slGfm/Vc9J5GhLm7rKMdMP9nC0ptERgEqKvVTlSpHMU7H+0=
    - secure: ZYkCUcWfunnL2TXsQ/VdkItG/lRU+T3+06j4Tbecw1O0DZNFJKT/MgNZJuhgT2ejNL9H5mHq9QTcXniieZ70fUpXKWd1hw3GDFxW+LkJAYJMzzTOrXkZRGFr0Q+cCbTeoeFan69knrNNN31MHm9PlF06kEKmvhqFCK8ZrL1NqsVGlZ8ukmI9W01L0/b2VUESnI/ymeClDjViura/EANsZH7Tpz42WNMT8sbH+72mAgETe3bBm5N1UkiK/6pa2YIS02/sJC7f8KdxGoYcdSzirh1ANfIegpWY1CvXRt++IZTza4okk5mbVpykOSFFom1jHdA0k+vcLmctW5OOt9SDh/aZrw4/jvl1DVawQGY3a7fNpPz1NJqI8lyuZYA8CtQ6zFcc5sjGbypmUJz+do2lUzdsCHidA4OEnZhbg2v1W/8ul/43KtUJpClmnejGKG1V+iVdqCB37MJwp3A9i4p8XwXSb7j+c+rGeh6pPVMiy51Nodipu1kMXwSkyLw+bZQOh8W4b3PU+3KqRigp1UkFCOIrBn6IGwpPwiR959b5fN4+wh0QbISu3lZOHBbJ6qRY0K4Dq2fCJXykEU/0BQiGVGAWgxEc/tgxwABVNeCYonlDPo4szil0Z79GWSrEyrjaiuP8hX+W8SGz0oLmvs5eXrkiQnmXxUZrFB1JgqPP3zg=
before_install:
  - openssl aes-256-cbc -K $encrypted_e3b08b1bff3b_key -iv $encrypted_e3b08b1bff3b_iv
    -in gcp_keyfile.json.enc -out gcp_keyfile.json -d
  - bash ./scripts/install_terraform
install:
  - export TF_VAR_project_name=$PROJECT_NAME
  - export TF_VAR_project_region=$PROJECT_REGION
script:
  - terraform init ${TF_INIT_CLI_OPTIONS} tf
  - terraform plan ${TF_PLAN_CLI_OPTIONS} tf
deploy:
  provider: script
  skip_cleanup: true
  on:
    branch: master
  script: >-
    terraform apply ${TF_APPLY_CLI_OPTIONS} tf &&
    terraform output ${TF_OUTPUT_CLI_OPTIONS} tf
