language: bash
cache:
  directories:
  - "$HOME/bin/terraform/"
env:
  global:
  - TF_VERSION=0.13.5
  - TF_INIT_CLI_OPTIONS="-input=false"
  - TF_PLAN_CLI_OPTIONS="-lock=false -input=false"
  - TF_APPLY_CLI_OPTIONS="-auto-approve -input=false"
  - TF_OUTPUT_CLI_OPTIONS=""
before_install:
- openssl aes-256-cbc -K $encrypted_e3b08b1bff3b_key -iv $encrypted_e3b08b1bff3b_iv
  -in gcp_keyfile.json.enc -out ./keyfiles/gcp_keyfile.json -d
- openssl aes-256-cbc -K $encrypted_9a919ae66310_key -iv $encrypted_9a919ae66310_iv
  -in terraform.tfvars.enc -out terraform.tfvars -d
- bash ./scripts/install_terraform
install:
- terraform init ${TF_INIT_CLI_OPTIONS}
script:
- terraform plan ${TF_PLAN_CLI_OPTIONS}
- terraform apply ${TF_APPLY_CLI_OPTIONS}
- terraform output ${TF_OUTPUT_CLI_OPTIONS}
