#!/bin/bash
set -e

# Download and install Terraform if correct version does not exist in cache
echo "Setting up Terraform version ${TF_VERSION}"
if [[ $(terraform --version) != *"$TF_VERSION"* ]]; then
  echo "Not found in cache - downloading and installing"
  rm -rf "$HOME"/bin/terraform
  wget https://releases.hashicorp.com/terraform/"$TF_VERSION"/terraform_"$TF_VERSION"_linux_amd64.zip &>/dev/null
  unzip terraform_"$TF_VERSION"_linux_amd64.zip &>/dev/null
  sudo mv terraform "$HOME"/bin &>/dev/null
  rm terraform_"$TF_VERSION"_linux_amd64.zip &>/dev/null
else
  echo "Found in cache - continuing"
fi
echo "Done setting up Terraform"
